### PR TITLE
Simple fix to change the output

### PR DESCRIPTION
**Pull request by fidian**
The variable in the environment is OPENTOKEN_CODE, not OPENTOKEN_KEY and
the parameter is --code instead of --key.

### CODE REVIEW

**Comment by fidian** [comment]
AGI-642
No dependencies.

**Comment by AbsentSemicolon** [comment]
Where is --code used? Is there documentation explaining using parameters, didn't see anything, or is it implied?

**Comment by fidian** [comment]
Agree.  I updated the pull request to add better documentation to the example script.  The --code parameter does not exist yet for any *.js examples.  Those need to be added this week.  Commit 1265209 for the fixes, commit 9d33fe1 to merge master into this branch.

**Comment by AbsentSemicolon** [comment]
Reviewed and looks good.

**Pull request merged**
