### PR TITLE
Adding .decodeForUri()

### PR DESCRIPTION
**Pull request by fidian**
This also converts the module to follow the same factory pattern as
found in the rest of the codebase.

### CODE REVIEW

**Comment by fidian** [comment]
No dependencies on other pull requests. AGI-735.

**Comment by AbsentSemicolon** [comment]
Missing tests for decodeForUri?

**Comment by fidian** [comment]
Fixed the problem of a missing test.

**Comment by AbsentSemicolon** [comment]
Reviewed and looks good.

**Pull request merged**
